# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy .Net to Azure Web App - DebtSnowballer-WebApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true


      - name: Build Client with dotnet
        run: dotnet build ./DebtSnowballer.App/DebtSnowballer/Client --configuration Release

      - name: Build Server with dotnet
        run: dotnet build ./DebtSnowballer.App/DebtSnowballer/Server --configuration Release

      - name: dotnet publish Client
        run: dotnet publish ./DebtSnowballer.App/DebtSnowballer/Client -c Release -o ${{env.DOTNET_ROOT}}\myapp

      - name: dotnet publish Server
        run: dotnet publish ./DebtSnowballer.App/DebtSnowballer/Server -c Release -o ${{env.DOTNET_ROOT}}\myapp


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DebtSnowballer-WebApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A2CCE828DA8E4200968E4AE34A0FF91D }}
          package: .
